sudo: required
services: 
  - docker

before_install:
  - docker build -t ankush1729/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ankush1729/react-test npm test -- --coverage

after_success:
  - docker build -t ankush1729/multi-client ./client
  - docker build -t ankush1729/multi-nginx ./nginx
  - docker build -t ankush1729/multi-server ./server
  - docker build -t ankush1729/multi-worker ./worker