sudo: required
services: 
  - docker

before_install:
  - docker build -t ankush1729/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ankush1729/react-test npm test

after_success:
  - docker build -t ankush1729/multi-client ./client
  - docker build -t ankush1729/multi-nginx ./nginx
  - docker build -t ankush1729/multi-server ./server
  - docker build -t ankush1729/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ankush1729/multi-client 
  - docker push ankush1729/multi-nginx
  - docker push ankush1729/multi-server
  - docker push ankush1729/multi-worker

deploy:

  provider: elasticbeanstalk

  region: "ap-south-1"

  app: "multi-docker"

  env: "Multidocker-env"

  bucket_name: "elasticbeanstalk-ap-south-1-051170420061"

  bucket_path: "multi-docker"

  on:

    branch: main

  access_key_id: $AWS_ACCESS_KEY

  secret_access_key: "$AWS_SECRET_KEY"